const fs = require("fs");
const path = require("path");

/**
 * Remove stray player-script.js files generated by yt-dlp
 */
function cleanStrayPlayerScripts(dirPath) {
    if (!fs.existsSync(dirPath)) return 0;
    
    let count = 0;
    try {
        const files = fs.readdirSync(dirPath);
        for (const file of files) {
            if (file.endsWith("-player-script.js") || file.includes("player-script")) {
                const fullPath = path.join(dirPath, file);
                try {
                    fs.unlinkSync(fullPath);
                    count++;
                    console.log(`[StorageCleaner] Removed stray script: ${file}`);
                } catch (err) {
                    console.error(`[StorageCleaner] Failed to delete ${file}:`, err.message);
                }
            }
        }
    } catch (err) {
        console.error(`[StorageCleaner] Error reading directory ${dirPath}:`, err.message);
    }
    return count;
}

/**
 * Remove files older than ttlMinutes from specified directories
 */
function cleanExpiredTempFiles(directories, ttlMinutes = 10) {
    let deletedCount = 0;
    const now = Date.now();
    const ttlMs = ttlMinutes * 60 * 1000;

    for (const dirPath of directories) {
        if (!fs.existsSync(dirPath)) continue;

        try {
            const files = fs.readdirSync(dirPath);
            for (const file of files) {
                if (file.startsWith(".")) continue;

                const fullPath = path.join(dirPath, file);
                try {
                    const stats = fs.statSync(fullPath);
                    if (stats.isFile()) {
                        const fileAge = now - stats.mtimeMs;
                        if (fileAge > ttlMs) {
                            fs.unlinkSync(fullPath);
                            deletedCount++;
                            console.log(`[StorageCleaner] Auto-deleted expired file (${Math.round(fileAge / 1000 / 60)}m old): ${file}`);
                        }
                    }
                } catch (err) {
                    console.error(`[StorageCleaner] Could not process file ${file}:`, err.message);
                }
            }
        } catch (err) {
            console.error(`[StorageCleaner] Error cleaning directory ${dirPath}:`, err.message);
        }
    }
    return deletedCount;
}

/**
 * Force empty all storage directories
 */
function emptyAllStorageFolders(directories) {
    let count = 0;
    for (const dirPath of directories) {
        if (!fs.existsSync(dirPath)) continue;
        try {
            const files = fs.readdirSync(dirPath);
            for (const file of files) {
                if (file.startsWith(".")) continue;
                const fullPath = path.join(dirPath, file);
                try {
                    const stats = fs.statSync(fullPath);
                    if (stats.isFile()) {
                        fs.unlinkSync(fullPath);
                        count++;
                    }
                } catch (err) {
                    console.error(`[StorageCleaner] Failed to unlink ${file}:`, err.message);
                }
            }
        } catch (err) {
            console.error(`[StorageCleaner] Error emptying ${dirPath}:`, err.message);
        }
    }
    return count;
}

/**
 * Delete a single file immediately with error handling
 */
function deleteFileImmediately(filePath) {
    if (!filePath || !fs.existsSync(filePath)) return false;
    try {
        fs.unlinkSync(filePath);
        console.log(`[StorageCleaner] Immediately deleted file after download: ${path.basename(filePath)}`);
        return true;
    } catch (err) {
        console.error(`[StorageCleaner] Error deleting file ${filePath}:`, err.message);
        return false;
    }
}

module.exports = {
    cleanStrayPlayerScripts,
    cleanExpiredTempFiles,
    emptyAllStorageFolders,
    deleteFileImmediately
};
